version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: c2c_tracking
