# fly.toml file generated for tracker-connect on 2022-09-02T12:09:34+02:00

app = "tracker-connect"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "brunobesson/tracker-connect:main"

[env]
  SERVER_BASE_URL="https://tracker-connect.fly.dev/"
  FRONTEND_BASE_URL="https://be00-80-12-86-157.eu.ngrok.io/"
  DB_PORT=5432
  DB_HOST="tracker-connect-db.internal"
  DB_USERNAME="postgres"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
