name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]
    tags: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install & lint
        run: |
          npm ci
          npm run lint
        env:
          CI: ${{ true }}
      # Note: we cannot set the command via github actions service containers
      # but minio image requires it. We thus rely on docker-compose.
      - name: Run minio for testing s3
        run: docker compose -f docker-compose.minio.yml up -d
      - name: npm test & build
        run: |
          npm run test:ci
          npm run build
        env:
          CI: ${{ true }}
      - name: Ensure docker-compose stopped
        run: docker compose -f docker-compose.minio.yml stop || true
        if: always()
      - name: Send coverage to codacy
        # secrets are not available for PR from forks, and dependabot PRs
        if: ${{ !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]' }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: reports/coverage/unit/lcov.info,reports/coverage/psql/lcov.info,reports/coverage/s3/lcov.info
      - name: Docker meta
        id: docker_meta
        if: "contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'"
        uses: docker/metadata-action@v5.6.1
        with:
          # list of Docker images to use as base name for tags
          images: ${{ github.repository }}
          # specify docker tags list so that git tags have precedence over branch
          # first tag will be used as version
          tags: |
            type=ref,event=tag,priority=610
            type=ref,event=branch,priority=600
      - name: Login to DockerHub
        if: "contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        if: "contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: version=${{ fromJSON(steps.docker_meta.outputs.json).labels['org.opencontainers.image.version'] }}

  create-release:
    needs: build
    if: "startsWith(github.ref, 'refs/tags/v')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
